replicaCount: 3 # Number of app pods to run in the cluster
image:
  repository: 896060361783.dkr.ecr.ap-south-1.amazonaws.com/my-nextjs-app
  tag: latest # The image tag to deploy (from GitHub Actions build)
  pullPolicy: IfNotPresent # Only pull if image is not already on the node
service:
  type: ClusterIP # Only accessible inside the cluster. Use LoadBalancer for public access.
  port: 80 # Exposed service port (targetPort in app must match containerPort)
resources:
  limits:
    cpu: '0.3' # Max CPU allowed per container
    memory: 256Mi # Max memory per container
  requests:
    cpu: '0.1' # Guaranteed CPU reservation
    memory: 128Mi # Guaranteed memory reservation